---
version: "2.2"
volumes:
  tf-data: {}
services:
  aws:
    image: amazon/aws-cli:2.2.9
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ROLE_ARN
  terraform:
    image: carlosnunez/terraform:1.3.0
    env_file: .env
    working_dir: /app
    environment:
      - TF_DATA_DIR=/data/.terraform
      - TF_VAR_domain_name=$DOMAIN_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_SESSION_TOKEN
    volumes:
      - tf-data:/data
      - $PWD:/app
      - $PWD/scripts:/scripts
    entrypoint:
      - /scripts/execute_terraform.sh
  verify:
    extends: terraform
    command:
      - plan
  deploy:
    extends: terraform
    command:
      - apply
      - -auto-approve
  destroy:
    extends: terraform
    command:
      - destroy
      - -auto-approve
  obtain-aws-session-token:
    extends: aws
    command:
      - sts
      - assume-role
      - --role-arn
      - "$AWS_ROLE_ARN"
      - --external-id
      - "$AWS_STS_EXTERNAL_ID"
      - --role-session-name
      - "$AWS_SESSION_NAME"
      - --output
      - yaml

