---
version: "2.2"
services:
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    entrypoint: /scripts/execute_terraform.sh
    env_file: .env
    working_dir: /app
    environment:
      TF_VAR_domain_name: $DOMAIN_NAME
      TF_DATA_DIR: /app/.terraform
    volumes:
      - $PWD:/app
  verify:
    extends: terraform
    command:
      - plan
  deploy:
    extends: terraform
    command:
      - apply
      - -auto-approve
  destroy:
    extends: terraform
    command:
      - destroy
      - -auto-approve
