---
name: Update Carlos's Redirects
on:
  push:
    branches:
      - main
    paths:
      - '*/**'
      - '!README.md'
      - '!bash_aliases'
      - '!*.Dockerfile'
jobs:
  update-redirects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt environment file
        run: docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
      - name: CRUD the infrastructure
        run: scripts/deploy.sh
